# https://github.com/dgtlmoon/changedetection.io/blob/master/docker-compose.yml
services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    user: 1005:1005
    hostname: changedetection
    volumes:
      - /mnt/2000/container-mounts/changedetection/data:/datastore
    environment:
      - PLAYWRIGHT_DRIVER_URL=ws://sockpuppetbrowser:3000
      #        Hides the `Referer` header so that monitored websites can't see the changedetection.io hostname.
      - HIDE_REFERER=true
    restart: no
    networks:
      - changedetection-net
    # https://github.com/dgtlmoon/changedetection.io/issues/1411#issuecomment-2274249829
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'python3 -c "import sys, urllib.request; sys.exit(1) if ''<title>Change Detection</title>'' not in urllib.request.urlopen(''http://localhost:5000'').read().decode(''utf-8'') else sys.exit(0)"',
        ]
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    labels:
      # For homepage
      - homepage.group=Reading
      - homepage.name=Change Detection
      - homepage.weight=30
      - homepage.icon=/dashboard-icons/svg/changedetection.svg
      - homepage.href=${HOME_PAGE_URL}
      - homepage.widget.type=changedetectionio
      - homepage.widget.key=${API_KEY}
      - homepage.widget.url=${HOME_PAGE_URL}
    # If WEBDRIVER or PLAYWRIGHT are enabled, changedetection container depends on that
    # and must wait before starting (substitute "browser-chrome" with "playwright-chrome" if last one is used)
    depends_on:
      - changedetection_sockpuppetbrowser
  # Sockpuppetbrowser is basically chrome wrapped in an API for allowing fast fetching of web-pages.
  # RECOMMENDED FOR FETCHING PAGES WITH CHROME
  changedetection_sockpuppetbrowser:
    container_name: changedetection-sockpuppetbrowser
    user: 1005:1005
    hostname: sockpuppetbrowser
    image: dgtlmoon/sockpuppetbrowser
    restart: no
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - MAX_CONCURRENT_CHROME_PROCESSES=10
    # https://github.com/dgtlmoon/sockpuppetbrowser
    healthcheck:
      test: wget --no-verbose -O - http://127.0.0.1:8080/stats 2>/dev/null | grep ",\ \"special_counter_len\":\ 0" || exit 1
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    networks:
      - changedetection-net
  ts:
    container_name: changedetection-ts
    image: tailscale/tailscale
    user: 1005:1005
    env_file: tailscale.env
    environment:
      - TS_HOSTNAME=changedetection
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/tailscale-config.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ENABLE_HEALTH_CHECK=true
      - TS_LOCAL_ADDR_PORT=127.0.0.1:9002
    volumes:
      - ./tailscale-state:/var/lib/tailscale
      - ./tailscale-config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    # https://github.com/tailscale/tailscale/issues/12758#issuecomment-2564770640
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:9002/healthz"]
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    networks:
      - changedetection-net
    restart: always
    depends_on:
      changedetection:
        condition: service_healthy
networks:
  changedetection-net:
volumes:
  changedetection-data:
