# https://hub.docker.com/r/uroni/urbackup-server
services:
  urbackup:
    build:
      context: ./urbackup
      dockerfile: Dockerfile
      args:
        VERSION: 2.5.33
    container_name: urbackup
    restart: no
    environment:
      - TZ=America/Chicago # Enter your timezone
    volumes:
      - /mnt/8000/container-mounts/urbackup/db:/var/urbackup
      - /mnt/8000/container-mounts/urbackup/backups:/backups
      - /home/chrisl8/credentials/server_update_location.url.download:/var/urbackup/server_update_location.url.download
      # Uncomment the next line if you want to bind-mount the www-folder
      #- /path/to/wwwfolder:/usr/share/urbackup
      # Unlike most of my containers, this one only runs locally,
      # so that it can see and be seen by computers on my local network using any and all ports,
      # while NOT seen remotely, because I never want backups to happen remotely at all, much less over Tailscale,
      # although it could be away to allow remote backups, I don't want to do that at the moment.
    network_mode: "host"
    labels:
      # For homepage
      - homepage.group=MiddleServices
      - homepage.name=UrBackup
      - homepage.weight=20
      - homepage.icon=urbackup.png # https://github.com/homarr-labs/dashboard-icons/
      - homepage.href=${HOME_PAGE_URL}
      - homepage.widget.type=urbackup
      - homepage.widget.url=${HOME_PAGE_URL}
      - homepage.widget.username=${URBACKUP_USERNAME}
      - homepage.widget.password=${URBACKUP_PASSWORD}
      - homepage.widget.fields=["ok", "errored", "noRecent", "totalUsed"]
      - homepage.widget.maxDays=7
    healthcheck:
      test: wget -O - http://127.0.0.1:55414 2> /dev/null | grep "UrBackup 2.5.33" || exit 1
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
