services:
  vaultwarden:
    image: vaultwarden/server
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - DOMAIN=${DOMAIN}
    volumes:
      - /mnt/2000/container-mounts/vaultwarden/data:/data/
    networks:
      - vaultwarden-net
    labels:
      # For homepage
      - homepage.group=Tools
      - homepage.name=Vaultwarden
      - homepage.weight=40
      - homepage.icon=/dashboard-icons/svg/vaultwarden.svg
      - homepage.href=${DOMAIN}
  ts:
    container_name: vaultwarden-ts
    image: tailscale/tailscale
    env_file: tailscale.env
    environment:
      - TS_HOSTNAME=vaultwarden
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/tailscale-config.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ENABLE_HEALTH_CHECK=true
      - TS_LOCAL_ADDR_PORT=127.0.0.1:9002
    volumes:
      - ./tailscale-state:/var/lib/tailscale
      - ./tailscale-config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    # https://github.com/tailscale/tailscale/issues/12758#issuecomment-2564770640
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:9002/healthz"]
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    networks:
      - vaultwarden-net
    restart: always
    depends_on:
      vaultwarden:
        condition: service_healthy
networks:
  vaultwarden-net:
