services:
  homepage:
    image: ghcr.io/gethomepage/homepage
    container_name: homepage
    user: 1011:1011
    # This must be the ID of the Docker group.
    group_add:
      - 985
      - 1000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - ./images:/app/public/images
      - ./icons:/app/public/icons
      - ./dashboard-icons:/app/public/dashboard-icons
      - /var/run/docker.sock:/var/run/docker.sock # pass local proxy
      # To allow homepage to show disk space free on all disks I have an empty folder on each disk that I mount here.
      - /home/chrisl8/for-homepage:/mnt/root
      - /mnt/120/for-homepage:/mnt/120
      - /mnt/250/for-homepage:/mnt/250
      - /mnt/2000/for-homepage:/mnt/2000
      - /mnt/22TB/for-homepage:/mnt/22TB
    restart: no
    networks:
      - homepage-net
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_HOST}
    # healthcheck: is built into this app, no need to add one.
  ts:
    container_name: homepage-ts
    user: 1011:1011
    image: tailscale/tailscale
    env_file: tailscale.env
    environment:
      - TS_HOSTNAME=console
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/tailscale-config.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ENABLE_HEALTH_CHECK=true
      - TS_LOCAL_ADDR_PORT=127.0.0.1:9002
    volumes:
      - ./tailscale-state:/var/lib/tailscale
      - ./tailscale-config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    # https://github.com/tailscale/tailscale/issues/12758#issuecomment-2564770640
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:9002/healthz"]
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    networks:
      - homepage-net
    restart: no
    depends_on:
      homepage:
        condition: service_healthy
networks:
  homepage-net:
