services:
  starbound:
    container_name: starbound
    user: 1026:1026
    build:
      dockerfile: Dockerfile
    restart: no
    environment:
      STEAM_USER: ${STEAM_USER}
    volumes:
      - /mnt/2000/container-mounts/starbound/starbound:/starbound
    #    network_mode: "host"
    ports:
      - 21025:21025
    healthcheck:
      test: pgrep -f starbound_server || exit 1
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
