services:
  diun:
    container_name: diun
    image: crazymax/diun:latest
    command: serve
    volumes:
      - /mnt/250a/container-mounts/diun/data:/data
      - ./diun.yml:/diun.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/Chicago
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 */6 * * *
      - DIUN_WATCH_JITTER=30s
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true
    labels:
      - "diun.enable=true"
    restart: always
    healthcheck:
      test: diun image list
      start_period: 30s
      interval: 120s
      timeout: 15s
      retries: 3
