services:
  diun:
    container_name: diun
    # This must be the ID of the Docker group.
    group_add:
      - 985
    image: crazymax/diun
    command: serve
    volumes:
      - /mnt/250/container-mounts/diun/data:/data
      - /mnt/250/container-mounts/diun/script:/script
      - ./diun.yml:/diun.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/Chicago
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 */6 * * *
      - DIUN_WATCH_JITTER=30s
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true
    labels:
      - "diun.enable=true"
    healthcheck:
      test: diun image list
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
# This doesn't even have a "front end", it just runs in the background and emails you when there are new images.
# I think it has to be run as root in order to do this though.
