services:
  uptime:
    container_name: uptime
    image: louislam/uptime-kuma
    volumes:
      - /mnt/2000/container-mounts/uptime/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - uptime-net
    restart: no
    labels:
      # For homepage
      - homepage.group=System Monitoring
      - homepage.name=Uptime
      - homepage.weight=20
      - homepage.icon=/dashboard-icons/svg/uptime-kuma.svg # https://github.com/homarr-labs/dashboard-icons/
      - homepage.href=${HOME_PAGE_URL}
      - homepage.widget.type=uptimekuma
      - homepage.widget.url=${HOME_PAGE_URL}
      - homepage.widget.slug=everything
      # Uptime has a built-in healthcheck
  ts:
    container_name: uptime-ts
    image: tailscale/tailscale
    env_file: tailscale.env
    environment:
      - TS_HOSTNAME=uptime
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/tailscale-config.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ENABLE_HEALTH_CHECK=true
      - TS_LOCAL_ADDR_PORT=127.0.0.1:9002
    volumes:
      - ./tailscale-state:/var/lib/tailscale
      - ./tailscale-config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    # https://github.com/tailscale/tailscale/issues/12758#issuecomment-2564770640
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:9002/healthz"]
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    networks:
      - uptime-net
    restart: always
    depends_on:
      uptime:
        condition: service_healthy
networks:
  uptime-net:
