services:
  brave:
    image: lscr.io/linuxserver/brave
    container_name: brave
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt/2000/container-mounts/brave-browser/config:/config
    shm_size: "1gb"
    restart: unless-stopped
    labels:
      # For homepage
      - homepage.group=Desktop Apps
      - homepage.name=Brave
      - homepage.weight=100
      - homepage.icon=/dashboard-icons/svg/brave.svg
      - homepage.href=${HOME_PAGE_URL}
    healthcheck:
      test: 'curl --fail http://brave:3000/manifest.json 2>/dev/null | grep -o "Brave" || exit 1'
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    networks:
      - brave-browser-net
  ts:
    container_name: brave-browser-ts
    image: tailscale/tailscale
    env_file: tailscale.env
    environment:
      - TS_HOSTNAME=brave-browser
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/tailscale-config.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ENABLE_HEALTH_CHECK=true
      - TS_LOCAL_ADDR_PORT=127.0.0.1:9002
    volumes:
      - ./tailscale-state:/var/lib/tailscale
      - ./tailscale-config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    # https://github.com/tailscale/tailscale/issues/12758#issuecomment-2564770640
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:9002/healthz"]
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    networks:
      - brave-browser-net
    restart: always
    depends_on:
      brave:
        condition: service_healthy
networks:
  brave-browser-net:
