services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - /mnt/250a/container-mounts/nginx/conf.d:/etc/nginx/conf.d
      - /mnt/250a/container-mounts/nginx/html:/html
    healthcheck:
      test: curl --fail http://localhost/ | grep "Welcome" || exit 1
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    networks:
      - nginx-net
    restart: always
    labels: # For homepage
      - homepage.group=MiddleServices
      - homepage.name=nginx
      - homepage.weight=500
      - homepage.icon=nginx.png # https://github.com/homarr-labs/dashboard-icons/
      - homepage.href=${HOME_PAGE_URL}
  ts:
    container_name: nginx-ts
    image: tailscale/tailscale
    env_file: tailscale.env
    environment:
      - TS_HOSTNAME=nginx
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/tailscale-config.json
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ./tailscale-state:/var/lib/tailscale
      - ./tailscale-config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    # https://github.com/tailscale/tailscale/issues/12758#issuecomment-2265152534
    healthcheck:
      test: tailscale status --peers=false --json | grep -q 'Online.*true'
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    networks:
      - nginx-net
    restart: always
    depends_on:
      nginx:
        condition: service_healthy
networks:
  nginx-net:
