services:
  mariadb:
    container_name: mariadb
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_AUTO_UPGRADE=1
      - TZ=America/Chicago
    volumes:
      - /mnt/2000/container-mounts/mariadb/db:/var/lib/mysql
    restart: no
    # Exposed locally so that my personal apps that use it don't have to traverse tailscale to use it.
    # This also means remote access is via the host's tailscale connection.
    ports:
      - "3306:3306"
    # https://mariadb.com/kb/en/using-healthcheck-sh/
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--connect",
          "--innodb_initialized",
          "--mariadbupgrade",
        ]
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
# There is no tailscale for this container, it is just exposed locally and can be connected to via the host's tailscale connection.
