services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - /mnt/250a/container-mounts/mariadb/db:/var/lib/mysql
    restart: always
    # Exposed locally so that my personal apps that use it don't have to traverse tailscale to use it.
    # This also means remote access is via the host's tailscale connection.
    ports:
      - "3306:3306"
    # https://mariadb.com/kb/en/using-healthcheck-sh/
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized", "--mariadbupgrade"]
      start_period: 30s
      interval: 120s
      timeout: 15s
      retries: 3
# There is no tailscale for this container, it is just exposed locally and can be connected to via the host's tailscale connection.
