services:
  photon:
    container_name: photon
    build:
      context: ./photon
      dockerfile: Dockerfile
      args:
        PHOTON_VERSION: 0.5.0
    volumes:
      - /mnt/3000/container-mounts/photon/data:/photon/photon_data
    networks:
      - photon-net
    restart: always
    healthcheck:
      test: 'curl --fail http://localhost:2322/status 2>/dev/null | grep -o "\"status\":\"Ok\"," || exit 1'
      start_period: 30s
      interval: 120s
      timeout: 15s
      retries: 3
  ts-photon:
    container_name: photon-ts
    image: tailscale/tailscale:latest
    env_file: tailscale.env
    environment:
      - TS_HOSTNAME=photon
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/tailscale-config.json
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ./tailscale-state:/var/lib/tailscale
      - ./tailscale-config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    # https://github.com/tailscale/tailscale/issues/12758#issuecomment-2265152534
    healthcheck:
      test: tailscale status --peers=false --json | grep -q 'Online.*true'
      start_period: 30s
      interval: 120s
      timeout: 15s
      retries: 3
    networks:
      - photon-net
    restart: always
    depends_on:
      - photon
networks:
  photon-net:
