#!/bin/bash
# Generates a user-config.yaml from the existing installation.
# Scans 1password_credential_paths.env files to find all required variables,
# marks currently enabled containers, and detects storage mounts.
set -e

YELLOW='\033[1;33m'
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/user-config.yaml"

if [[ -f "$CONFIG_FILE" ]]; then
  printf "${RED}user-config.yaml already exists at %s${NC}\n" "$CONFIG_FILE"
  echo "To regenerate, remove or rename it first."
  exit 1
fi

echo "Generating user-config.yaml from existing installation..."
echo ""

# Detect Docker GID
DOCKER_GID=$(getent group docker 2>/dev/null | cut -d: -f3)
DOCKER_GID=${DOCKER_GID:-985}
printf "${GREEN}Detected Docker group GID: %s${NC}\n" "$DOCKER_GID" >&2

{
  echo "# Auto-generated by migrate-to-registry.sh"
  echo "# Review and fill in any empty values."
  echo ""
  echo "mounts:"
  echo "  - path: \"/mnt/2000\""
  echo "    label: \"Primary SSD\""
  echo "  - path: \"/mnt/22TB\""
  echo "    label: \"Large HDD\""
  echo "  - path: \"/mnt/250\""
  echo "    label: \"Cache SSD\""
  echo "  - path: \"/mnt/120\""
  echo "    label: \"Monitor\""
  echo ""
  DETECTED_HOSTNAME=$(hostname)
  printf "${GREEN}Detected hostname: %s${NC}\n" "$DETECTED_HOSTNAME" >&2
  echo "shared:"
  echo "  TS_AUTHKEY: \"\""
  echo "  TS_DOMAIN: \"\""
  echo "  HOST_NAME: \"${DETECTED_HOSTNAME}\""
  echo "  DOCKER_GID: \"${DOCKER_GID}\""
  echo ""
  echo "containers:"

  CONTAINER_COUNT=0
  ENABLED_COUNT=0
  VAR_COUNT=0

  for dir in "${SCRIPT_DIR}"/*/; do
    dir_name=$(basename "$dir")
    compose_file="${dir}compose.yaml"
    [[ -f "$compose_file" ]] || continue

    CONTAINER_COUNT=$((CONTAINER_COUNT + 1))

    if [[ -f "${dir}_DISABLED_" ]]; then
      ENABLED=false
    else
      ENABLED=true
      ENABLED_COUNT=$((ENABLED_COUNT + 1))
    fi

    echo "  ${dir_name}:"
    echo "    enabled: ${ENABLED}"

    # Extract per-volume mount assignments based on the old ROOT variable mapping
    # DATA_ROOT -> mount 0, MEDIA_ROOT -> mount 1, CACHE_ROOT -> mount 2, MONITOR_ROOT -> mount 3
    HAS_VOL_MOUNTS=false
    VOL_MOUNTS=""
    while IFS= read -r line; do
      var_name=$(echo "$line" | grep -oP 'VOL_[A-Z0-9_]+' | head -1)
      # Determine mount index from the original compose context
      # We check git diff to find which ROOT var was used originally
      # But since we already rewrote, use the default as ~/container-data
      # The migration for existing installs should detect from the compose defaults
      :
    done < <(grep 'VOL_' "$compose_file" 2>/dev/null || true)

    # Check for 1password credential paths
    OP_ENV="${dir}1password_credential_paths.env"
    if [[ -f "$OP_ENV" ]]; then
      VARS=$(grep -E '^[A-Z]' "$OP_ENV" | grep -v '^TS_AUTHKEY\|^TS_DOMAIN\|^HOST_NAME' | sed 's/:*=.*//' | sort)
      if [[ -n "$VARS" ]]; then
        echo "    variables:"
        while IFS= read -r var; do
          echo "      ${var}: \"\""
          VAR_COUNT=$((VAR_COUNT + 1))
        done <<< "$VARS"
      fi
    fi
  done

} > "$CONFIG_FILE"

echo ""
printf "${GREEN}Created %s${NC}\n" "$CONFIG_FILE"
echo ""
echo "Summary:"
echo "  Containers found: ${CONTAINER_COUNT}"
echo "  Currently enabled: ${ENABLED_COUNT}"
echo "  Variables to configure: ${VAR_COUNT}"
echo ""
echo "Next steps:"
echo "  1. Fill in shared variables (TS_AUTHKEY, TS_DOMAIN, etc.)"
echo "  2. Fill in per-container variable values"
echo "  3. Adjust mount paths if yours differ from the defaults"
echo "  4. Or use the web-admin Configuration tab to do all of this"
echo ""
