#!/bin/bash
# Generates a user-config.yaml from the existing installation.
# Scans 1password_credential_paths.env files to find all required variables,
# marks currently enabled containers, and populates shared variables with
# current mount paths.
set -e

YELLOW='\033[1;33m'
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/user-config.yaml"

if [[ -f "$CONFIG_FILE" ]]; then
  printf "${RED}user-config.yaml already exists at %s${NC}\n" "$CONFIG_FILE"
  echo "To regenerate, remove or rename it first."
  exit 1
fi

echo "Generating user-config.yaml from existing installation..."
echo ""

# Build the config
{
  echo "# Auto-generated by migrate-to-registry.sh"
  echo "# Review and fill in any empty values."
  echo ""
  echo "shared:"
  echo "  DATA_ROOT: \"/mnt/2000\""
  echo "  MEDIA_ROOT: \"/mnt/22TB\""
  echo "  CACHE_ROOT: \"/mnt/250\""
  echo "  MONITOR_ROOT: \"/mnt/120\""
  echo "  TS_AUTHKEY: \"\""
  echo "  TS_DOMAIN: \"\""
  echo "  HOST_NAME: \"\""
  echo "  DOCKER_GID: \"985\""
  echo ""

  # Detect Docker GID
  DOCKER_GID=$(getent group docker 2>/dev/null | cut -d: -f3)
  if [[ -n "$DOCKER_GID" ]]; then
    printf "${GREEN}Detected Docker group GID: %s${NC}\n" "$DOCKER_GID" >&2
    # Re-emit with detected GID (we already printed the default above, but
    # we'll note it in a comment)
  fi

  echo "containers:"

  CONTAINER_COUNT=0
  ENABLED_COUNT=0
  VAR_COUNT=0

  for dir in "${SCRIPT_DIR}"/*/; do
    dir_name=$(basename "$dir")
    compose_file="${dir}compose.yaml"

    # Skip if no compose.yaml
    [[ -f "$compose_file" ]] || continue

    CONTAINER_COUNT=$((CONTAINER_COUNT + 1))

    # Check if disabled
    if [[ -f "${dir}_DISABLED_" ]]; then
      ENABLED=false
    else
      ENABLED=true
      ENABLED_COUNT=$((ENABLED_COUNT + 1))
    fi

    echo "  ${dir_name}:"
    echo "    enabled: ${ENABLED}"

    # Check for 1password credential paths
    OP_ENV="${dir}1password_credential_paths.env"
    if [[ -f "$OP_ENV" ]]; then
      # Extract non-shared variable names
      VARS=$(grep -E '^[A-Z]' "$OP_ENV" | grep -v '^TS_AUTHKEY\|^TS_DOMAIN\|^HOST_NAME' | sed 's/:*=.*//' | sort)
      if [[ -n "$VARS" ]]; then
        echo "    variables:"
        while IFS= read -r var; do
          echo "      ${var}: \"\""
          VAR_COUNT=$((VAR_COUNT + 1))
        done <<< "$VARS"
      fi
    fi
  done

} > "$CONFIG_FILE"

echo ""
printf "${GREEN}Created %s${NC}\n" "$CONFIG_FILE"
echo ""
echo "Summary:"
echo "  Containers found: ${CONTAINER_COUNT}"
echo "  Currently enabled: ${ENABLED_COUNT}"
echo "  Variables to configure: ${VAR_COUNT}"
echo ""
echo "Next steps:"
echo "  1. Fill in shared variables (TS_AUTHKEY, TS_DOMAIN, etc.)"
echo "  2. Fill in per-container variable values"
echo "  3. Or use the web-admin Configuration tab to fill them in"
echo ""
