#!/bin/bash
# Sets up Infisical as the self-hosted secret manager.
# This script:
# 1. Generates encryption keys and DB password
# 2. Creates/updates the Infisical .env file
# 3. Starts the Infisical stack
# 4. Bootstraps an admin account and machine identity
# 5. Creates the "Containers" project with /shared folder
# 6. Saves machine identity credentials to ~/credentials/infisical.env
set -e

YELLOW='\033[1;33m'
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INFISICAL_DIR="${SCRIPT_DIR}/infisical"
CRED_FILE="${HOME}/credentials/infisical.env"
SECRETS_FILE="${INFISICAL_DIR}/infisical-secrets.env"

# Check prerequisites
if ! command -v infisical &>/dev/null; then
  printf "${RED}Infisical CLI is not installed.${NC}\n"
  echo "Install it from: https://infisical.com/docs/cli/overview"
  echo ""
  echo "Quick install:"
  echo "  curl -1sLf 'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' | sudo bash"
  echo "  sudo apt-get install infisical"
  exit 1
fi

if ! command -v docker &>/dev/null; then
  printf "${RED}Docker is not installed.${NC}\n"
  exit 1
fi

echo ""
echo "=== Infisical Secret Manager Setup ==="
echo ""

# 1. Generate Infisical-specific secrets if not already created
if [[ ! -f "$SECRETS_FILE" ]]; then
  printf "${YELLOW}Generating encryption keys...${NC}\n"
  AUTH_SECRET=$(openssl rand -hex 32)
  ENCRYPTION_KEY=$(openssl rand -hex 16)
  DB_PASSWORD=$(openssl rand -hex 16)

  cat > "$SECRETS_FILE" << EOF
# Infisical internal secrets (auto-generated by setup-infisical.sh)
AUTH_SECRET=${AUTH_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
DB_PASSWORD=${DB_PASSWORD}
EOF
  chmod 600 "$SECRETS_FILE"
  printf "${GREEN}Created %s${NC}\n" "$SECRETS_FILE"
else
  printf "${GREEN}Infisical secrets file already exists, keeping it.${NC}\n"
fi

# 2. Build the .env file for Docker Compose
# Start with registry-generated config (volume paths, Tailscale vars)
USER_CONFIG="${SCRIPT_DIR}/user-config.yaml"
if [[ -f "$USER_CONFIG" ]] && command -v node &>/dev/null; then
  node "${SCRIPT_DIR}/scripts/generate-env.js" infisical --quiet 2>/dev/null || true
fi

# Append Infisical-specific secrets to the .env file IF they aren't already
# there. generate-env.js (called above) also appends them via its
# appendInfisicalBootstrapSecrets path, so this is a defensive idempotency
# check to avoid duplicating the secrets section on every run. The fallback
# branch handles the case where generate-env.js didn't run (no
# user-config.yaml or no node) and the .env file doesn't exist yet.
if [[ -f "${INFISICAL_DIR}/.env" ]]; then
  if ! grep -q '^AUTH_SECRET=' "${INFISICAL_DIR}/.env"; then
    echo "" >> "${INFISICAL_DIR}/.env"
    echo "# Infisical internal secrets" >> "${INFISICAL_DIR}/.env"
    grep -v '^#' "$SECRETS_FILE" | grep -v '^$' >> "${INFISICAL_DIR}/.env"
  fi
else
  cp "$SECRETS_FILE" "${INFISICAL_DIR}/.env"
fi

# 3. Start the Infisical services
printf "${YELLOW}Starting Infisical core services...${NC}\n"
cd "$INFISICAL_DIR"
# Don't use --wait here -- Infisical takes time for DB migrations on first boot.
# We poll the API directly below.
docker compose up -d

# 4. Wait for the API to be ready (may take a few minutes on first boot due to migrations)
printf "${YELLOW}Waiting for Infisical API (first boot may take a few minutes)...${NC}\n"
for i in $(seq 1 90); do
  if curl -sf http://localhost:8085/api/status > /dev/null 2>&1; then
    break
  fi
  if [[ $i -eq 90 ]]; then
    printf "${RED}Infisical API did not become ready in time.${NC}\n"
    printf "${RED}Check logs with: docker logs infisical${NC}\n"
    exit 1
  fi
  sleep 2
done
printf "${GREEN}Infisical API is ready on http://localhost:8085${NC}\n"

# 5. Bootstrap admin + machine identity
mkdir -p "${HOME}/credentials"

if [[ -f "$CRED_FILE" ]]; then
  printf "${GREEN}Infisical credentials already exist at %s${NC}\n" "$CRED_FILE"
  echo "To re-bootstrap, remove this file first."
else
  printf "${YELLOW}Bootstrapping Infisical...${NC}\n"

  ADMIN_EMAIL="admin@infisical.local"
  ADMIN_PASSWORD=$(openssl rand -hex 16)

  # Persist the generated password BEFORE bootstrapping. Bootstrapping is one-shot:
  # once an instance is set up, `--ignore-if-bootstrapped` exits 0 printing NOTHING
  # and cannot re-issue a token. Writing the password only at the end (as this
  # script used to) means any failure in between strands the instance with an admin
  # password that was never recorded -- unrecoverable short of destroying the
  # database. Keep these breadcrumbs until the real credentials file is written.
  BOOTSTRAP_STATE="${HOME}/credentials/infisical-bootstrap-state.env"
  BOOTSTRAP_RAW="${HOME}/credentials/infisical-bootstrap-raw.json"
  BOOTSTRAP_ERR="${HOME}/credentials/infisical-bootstrap.err"
  (
    umask 077
    cat > "$BOOTSTRAP_STATE" << EOF
# Written before 'infisical bootstrap' so a mid-flight failure stays recoverable.
# Safe to delete once ${CRED_FILE} exists.
INFISICAL_ADMIN_EMAIL=${ADMIN_EMAIL}
INFISICAL_ADMIN_PASSWORD=${ADMIN_PASSWORD}
EOF
  )

  # Capture stdout ONLY. The CLI prints "A new release of infisical is available"
  # to stderr, and the old `2>&1` folded that banner into the JSON, so the parse
  # below failed on every host whose CLI was not the very newest -- which is most
  # of them. The failure was silent because the token then came back empty.
  BOOTSTRAP_OUTPUT=$(infisical bootstrap \
    --domain="http://localhost:8085" \
    --email="$ADMIN_EMAIL" \
    --password="$ADMIN_PASSWORD" \
    --organization="Self-Hosted" \
    --ignore-if-bootstrapped 2> "$BOOTSTRAP_ERR") || true
  ( umask 077; printf '%s' "$BOOTSTRAP_OUTPUT" > "$BOOTSTRAP_RAW" )

  # Extract the machine identity token
  IDENTITY_TOKEN=$(echo "$BOOTSTRAP_OUTPUT" | node -e "
    let data=''; process.stdin.on('data',d=>data+=d); process.stdin.on('end',()=>{
      try { const j=JSON.parse(data); console.log(j.identity.credentials.token); }
      catch(e) { process.exit(1); }
    });
  " 2>/dev/null)

  if [[ -z "$IDENTITY_TOKEN" ]]; then
    printf "${RED}Failed to obtain a machine identity token from bootstrap.${NC}\n"
    if [[ -z "${BOOTSTRAP_OUTPUT//[[:space:]]/}" ]]; then
      # The distinguishing symptom: success and "already done" both exit 0, but
      # only the latter prints nothing at all.
      printf "${RED}Bootstrap returned no output, which means this instance was ALREADY${NC}\n"
      printf "${RED}set up. --ignore-if-bootstrapped exits 0 silently in that case and cannot${NC}\n"
      printf "${RED}re-issue a token. Either:${NC}\n"
      printf "${RED}  - log in with the admin credentials saved at${NC}\n"
      printf "${RED}    %s and create a machine identity by hand, or${NC}\n" "$BOOTSTRAP_STATE"
      printf "${RED}  - stop the stack, delete the Postgres data directory, and re-run this${NC}\n"
      printf "${RED}    script to bootstrap a genuinely clean instance.${NC}\n"
    else
      printf "${RED}Could not parse the bootstrap response. Raw output:${NC}\n"
      echo "$BOOTSTRAP_OUTPUT"
      if [[ -s "$BOOTSTRAP_ERR" ]]; then
        printf "${RED}stderr:${NC}\n"
        cat "$BOOTSTRAP_ERR"
      fi
    fi
    printf "${RED}Admin credentials from this run are preserved at %s${NC}\n" "$BOOTSTRAP_STATE"
    exit 1
  fi

  # Extract organization ID
  ORG_ID=$(echo "$BOOTSTRAP_OUTPUT" | node -e "
    let data=''; process.stdin.on('data',d=>data+=d); process.stdin.on('end',()=>{
      try { const j=JSON.parse(data); console.log(j.organization.id); }
      catch(e) { process.exit(1); }
    });
  " 2>/dev/null)

  # Extract the machine identity's own ID (distinct from the token above)
  IDENTITY_ID=$(echo "$BOOTSTRAP_OUTPUT" | node -e "
    let data=''; process.stdin.on('data',d=>data+=d); process.stdin.on('end',()=>{
      try { const j=JSON.parse(data); console.log(j.identity.id); }
      catch(e) { process.exit(1); }
    });
  " 2>/dev/null)

  printf "${GREEN}Bootstrap successful.${NC}\n"

  # Infisical's token-auth method treats accessTokenTTL/accessTokenMaxTTL of 0 as
  # "no override configured" and silently falls back to a short internal default
  # (observed: the bootstrap token died after ~7 days with "Identity access token
  # exceeded max age", even though its own DB record showed accessTokenMaxTTL: 0,
  # which the API/UI otherwise documents as meaning unlimited). Explicitly setting
  # a large non-zero TTL/maxTTL sidesteps the bug. Do this BEFORE anything else
  # touches the identity, using the still-fresh bootstrap token as the bearer —
  # the identity has org-admin rights over itself.
  printf "${YELLOW}Setting a long-lived (10yr) token TTL/maxTTL for the machine identity...${NC}\n"
  curl -sf -X PATCH "http://localhost:8085/api/v1/auth/token-auth/identities/${IDENTITY_ID}" \
    -H "Authorization: Bearer ${IDENTITY_TOKEN}" \
    -H "Content-Type: application/json" \
    -d '{"accessTokenTTL":315360000,"accessTokenMaxTTL":315360000}' > /dev/null 2>&1 || \
    printf "${YELLOW}Could not set long-lived TTL — the bootstrap token may hit the ~7-day max-age bug. See docs/INFISICAL_UPGRADE_RUNBOOK.md.${NC}\n"

  # Re-issue the token now that the identity's default TTL/maxTTL is fixed —
  # unlike the bootstrap token (which has no baked-in JWT `exp` and relies on the
  # buggy server-side maxTTL check), a token minted via this endpoint bakes the
  # correct 10yr `exp` directly into the JWT, so it can't hit the same bug.
  REISSUE_OUTPUT=$(curl -sf -X POST "http://localhost:8085/api/v1/auth/token-auth/identities/${IDENTITY_ID}/tokens" \
    -H "Authorization: Bearer ${IDENTITY_TOKEN}" \
    -H "Content-Type: application/json" \
    -d '{"name":"cron-scripts-token"}' 2>/dev/null) || true
  REISSUED_TOKEN=$(echo "$REISSUE_OUTPUT" | node -e "
    let data=''; process.stdin.on('data',d=>data+=d); process.stdin.on('end',()=>{
      try { const j=JSON.parse(data); console.log(j.accessToken); }
      catch(e) { process.exit(1); }
    });
  " 2>/dev/null)
  if [[ -n "$REISSUED_TOKEN" ]]; then
    IDENTITY_TOKEN="$REISSUED_TOKEN"
    printf "${GREEN}Re-issued a long-lived token.${NC}\n"
  else
    printf "${YELLOW}Could not re-issue a long-lived token — keeping the original bootstrap token.${NC}\n"
  fi

  # 6. Create the "Containers" project
  printf "${YELLOW}Creating Containers project...${NC}\n"
  PROJECT_OUTPUT=$(curl -sf "http://localhost:8085/api/v2/workspace" \
    -H "Authorization: Bearer ${IDENTITY_TOKEN}" \
    -H "Content-Type: application/json" \
    -d "{\"projectName\": \"Containers\", \"organizationId\": \"${ORG_ID}\"}" 2>&1) || true

  PROJECT_ID=$(echo "$PROJECT_OUTPUT" | node -e "
    let data=''; process.stdin.on('data',d=>data+=d); process.stdin.on('end',()=>{
      try { const j=JSON.parse(data); console.log(j.project?.id || j.workspace?.id || ''); }
      catch(e) { process.exit(1); }
    });
  " 2>/dev/null)

  if [[ -z "$PROJECT_ID" ]]; then
    printf "${YELLOW}Could not auto-create project. You may need to create it in the Infisical UI.${NC}\n"
    echo "API response: $PROJECT_OUTPUT"
    PROJECT_ID="FILL_IN_FROM_UI"
  else
    printf "${GREEN}Created project: %s${NC}\n" "$PROJECT_ID"

    # Create /shared folder
    curl -sf "http://localhost:8085/api/v1/folders" \
      -H "Authorization: Bearer ${IDENTITY_TOKEN}" \
      -H "Content-Type: application/json" \
      -d "{\"workspaceId\": \"${PROJECT_ID}\", \"environment\": \"prod\", \"name\": \"shared\", \"path\": \"/\"}" > /dev/null 2>&1 || true
    printf "${GREEN}Created /shared folder.${NC}\n"

    # Auto-detect and write HOST_NAME and DOCKER_GID to /shared
    DETECTED_HOSTNAME=$(hostname)
    DETECTED_DOCKER_GID=$(getent group docker 2>/dev/null | cut -d: -f3)
    DETECTED_DOCKER_GID=${DETECTED_DOCKER_GID:-985}
    printf "${YELLOW}Writing auto-detected HOST_NAME=%s and DOCKER_GID=%s to Infisical...${NC}\n" "$DETECTED_HOSTNAME" "$DETECTED_DOCKER_GID"
    curl -sf "http://localhost:8085/api/v3/secrets/raw/HOST_NAME" \
      -X POST \
      -H "Authorization: Bearer ${IDENTITY_TOKEN}" \
      -H "Content-Type: application/json" \
      -d "{\"workspaceId\": \"${PROJECT_ID}\", \"environment\": \"prod\", \"secretPath\": \"/shared\", \"secretValue\": \"${DETECTED_HOSTNAME}\", \"type\": \"shared\"}" > /dev/null 2>&1 || true
    curl -sf "http://localhost:8085/api/v3/secrets/raw/DOCKER_GID" \
      -X POST \
      -H "Authorization: Bearer ${IDENTITY_TOKEN}" \
      -H "Content-Type: application/json" \
      -d "{\"workspaceId\": \"${PROJECT_ID}\", \"environment\": \"prod\", \"secretPath\": \"/shared\", \"secretValue\": \"${DETECTED_DOCKER_GID}\", \"type\": \"shared\"}" > /dev/null 2>&1 || true
  fi

  # Save credentials
  cat > "$CRED_FILE" << EOF
# Infisical machine identity credentials
# Generated by setup-infisical.sh
INFISICAL_TOKEN=${IDENTITY_TOKEN}
INFISICAL_PROJECT_ID=${PROJECT_ID}
INFISICAL_API_URL=http://localhost:8085
INFISICAL_ADMIN_EMAIL=${ADMIN_EMAIL}
INFISICAL_ADMIN_PASSWORD=${ADMIN_PASSWORD}
EOF
  chmod 600 "$CRED_FILE"
  printf "${GREEN}Saved credentials to %s${NC}\n" "$CRED_FILE"

  # The real credentials file now exists, so the pre-bootstrap breadcrumbs are
  # redundant copies of the same secrets -- drop them.
  rm -f "$BOOTSTRAP_STATE" "$BOOTSTRAP_RAW" "$BOOTSTRAP_ERR"
fi

printf "${GREEN}Infisical secret manager ready.${NC}\n"
