#!/bin/bash
# Sets up Infisical as the self-hosted secret manager.
# This script:
# 1. Generates encryption keys and DB password
# 2. Creates/updates the Infisical .env file
# 3. Starts the Infisical stack
# 4. Bootstraps an admin account and machine identity
# 5. Creates the "Containers" project with /shared folder
# 6. Saves machine identity credentials to ~/credentials/infisical.env
set -e

YELLOW='\033[1;33m'
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INFISICAL_DIR="${SCRIPT_DIR}/infisical"
CRED_FILE="${HOME}/credentials/infisical.env"
SECRETS_FILE="${INFISICAL_DIR}/infisical-secrets.env"

# Check prerequisites
if ! command -v infisical &>/dev/null; then
  printf "${RED}Infisical CLI is not installed.${NC}\n"
  echo "Install it from: https://infisical.com/docs/cli/overview"
  echo ""
  echo "Quick install:"
  echo "  curl -1sLf 'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' | sudo bash"
  echo "  sudo apt-get install infisical"
  exit 1
fi

if ! command -v docker &>/dev/null; then
  printf "${RED}Docker is not installed.${NC}\n"
  exit 1
fi

echo ""
echo "=== Infisical Secret Manager Setup ==="
echo ""

# 1. Generate Infisical-specific secrets if not already created
if [[ ! -f "$SECRETS_FILE" ]]; then
  printf "${YELLOW}Generating encryption keys...${NC}\n"
  AUTH_SECRET=$(openssl rand -hex 32)
  ENCRYPTION_KEY=$(openssl rand -hex 16)
  DB_PASSWORD=$(openssl rand -hex 16)

  cat > "$SECRETS_FILE" << EOF
# Infisical internal secrets (auto-generated by setup-infisical.sh)
AUTH_SECRET=${AUTH_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
DB_PASSWORD=${DB_PASSWORD}
EOF
  chmod 600 "$SECRETS_FILE"
  printf "${GREEN}Created %s${NC}\n" "$SECRETS_FILE"
else
  printf "${GREEN}Infisical secrets file already exists, keeping it.${NC}\n"
fi

# 2. Build the .env file for Docker Compose
# Start with registry-generated config (volume paths, Tailscale vars)
USER_CONFIG="${SCRIPT_DIR}/user-config.yaml"
if [[ -f "$USER_CONFIG" ]] && command -v node &>/dev/null; then
  node "${SCRIPT_DIR}/scripts/generate-env.js" infisical --quiet 2>/dev/null || true
fi

# Append Infisical-specific secrets to the .env file
# (generate-env.js writes volume paths and Tailscale vars; we add DB_PASSWORD etc.)
if [[ -f "${INFISICAL_DIR}/.env" ]]; then
  echo "" >> "${INFISICAL_DIR}/.env"
  echo "# Infisical internal secrets" >> "${INFISICAL_DIR}/.env"
  grep -v '^#' "$SECRETS_FILE" | grep -v '^$' >> "${INFISICAL_DIR}/.env"
else
  cp "$SECRETS_FILE" "${INFISICAL_DIR}/.env"
fi

# 3. Start the core Infisical services (skip Tailscale -- credentials aren't set yet)
printf "${YELLOW}Starting Infisical core services...${NC}\n"
cd "$INFISICAL_DIR"
docker compose up -d --wait infisical infisical-db infisical-redis
printf "${GREEN}Infisical is running on http://localhost:8085${NC}\n"

# 4. Wait for the API to be ready
printf "${YELLOW}Waiting for Infisical API...${NC}\n"
for i in $(seq 1 30); do
  if curl -sf http://localhost:8085/api/status > /dev/null 2>&1; then
    break
  fi
  if [[ $i -eq 30 ]]; then
    printf "${RED}Infisical API did not become ready in time.${NC}\n"
    exit 1
  fi
  sleep 2
done
printf "${GREEN}Infisical API is ready.${NC}\n"

# 5. Bootstrap admin + machine identity
mkdir -p "${HOME}/credentials"

if [[ -f "$CRED_FILE" ]]; then
  printf "${GREEN}Infisical credentials already exist at %s${NC}\n" "$CRED_FILE"
  echo "To re-bootstrap, remove this file first."
else
  printf "${YELLOW}Bootstrapping Infisical...${NC}\n"

  ADMIN_EMAIL="admin@localhost"
  ADMIN_PASSWORD=$(openssl rand -hex 16)

  BOOTSTRAP_OUTPUT=$(infisical bootstrap \
    --domain="http://localhost:8085" \
    --email="$ADMIN_EMAIL" \
    --password="$ADMIN_PASSWORD" \
    --organization="Self-Hosted" \
    --ignore-if-bootstrapped 2>&1)

  # Extract the machine identity token
  IDENTITY_TOKEN=$(echo "$BOOTSTRAP_OUTPUT" | node -e "
    let data=''; process.stdin.on('data',d=>data+=d); process.stdin.on('end',()=>{
      try { const j=JSON.parse(data); console.log(j.identity.credentials.token); }
      catch(e) { process.exit(1); }
    });
  " 2>/dev/null)

  if [[ -z "$IDENTITY_TOKEN" ]]; then
    printf "${RED}Failed to extract identity token from bootstrap output.${NC}\n"
    echo "Bootstrap output:"
    echo "$BOOTSTRAP_OUTPUT"
    exit 1
  fi

  # Extract organization ID
  ORG_ID=$(echo "$BOOTSTRAP_OUTPUT" | node -e "
    let data=''; process.stdin.on('data',d=>data+=d); process.stdin.on('end',()=>{
      try { const j=JSON.parse(data); console.log(j.organization.id); }
      catch(e) { process.exit(1); }
    });
  " 2>/dev/null)

  printf "${GREEN}Bootstrap successful.${NC}\n"

  # 6. Create the "Containers" project
  printf "${YELLOW}Creating Containers project...${NC}\n"
  PROJECT_OUTPUT=$(curl -sf "http://localhost:8085/api/v2/workspace" \
    -H "Authorization: Bearer ${IDENTITY_TOKEN}" \
    -H "Content-Type: application/json" \
    -d "{\"projectName\": \"Containers\", \"organizationId\": \"${ORG_ID}\"}" 2>&1) || true

  PROJECT_ID=$(echo "$PROJECT_OUTPUT" | node -e "
    let data=''; process.stdin.on('data',d=>data+=d); process.stdin.on('end',()=>{
      try { const j=JSON.parse(data); console.log(j.project?.id || j.workspace?.id || ''); }
      catch(e) { process.exit(1); }
    });
  " 2>/dev/null)

  if [[ -z "$PROJECT_ID" ]]; then
    printf "${YELLOW}Could not auto-create project. You may need to create it in the Infisical UI.${NC}\n"
    echo "API response: $PROJECT_OUTPUT"
    PROJECT_ID="FILL_IN_FROM_UI"
  else
    printf "${GREEN}Created project: %s${NC}\n" "$PROJECT_ID"

    # Create /shared folder
    curl -sf "http://localhost:8085/api/v2/folders" \
      -H "Authorization: Bearer ${IDENTITY_TOKEN}" \
      -H "Content-Type: application/json" \
      -d "{\"projectId\": \"${PROJECT_ID}\", \"environment\": \"prod\", \"name\": \"shared\"}" > /dev/null 2>&1 || true
    printf "${GREEN}Created /shared folder.${NC}\n"
  fi

  # Save credentials
  cat > "$CRED_FILE" << EOF
# Infisical machine identity credentials
# Generated by setup-infisical.sh
INFISICAL_TOKEN=${IDENTITY_TOKEN}
INFISICAL_PROJECT_ID=${PROJECT_ID}
INFISICAL_API_URL=http://localhost:8085
INFISICAL_ADMIN_EMAIL=${ADMIN_EMAIL}
INFISICAL_ADMIN_PASSWORD=${ADMIN_PASSWORD}
EOF
  chmod 600 "$CRED_FILE"
  printf "${GREEN}Saved credentials to %s${NC}\n" "$CRED_FILE"
fi

echo ""
echo "============================================"
printf "${GREEN}Infisical Setup Complete!${NC}\n"
echo "============================================"
echo ""
echo "Credentials: ${CRED_FILE}"
echo ""
echo "Next steps:"
echo "  1. Open the Infisical web UI to verify it's running"
echo "  2. Use the web-admin Configuration tab to set secrets"
echo "     (they'll be stored in Infisical automatically)"
echo "  3. Or run scripts/migrate-1password-to-infisical.sh to"
echo "     import existing secrets from 1Password"
echo ""
