services:
  minecraft:
    container_name: minecraft
    build:
      context: ./docker-minecraft-bedrock-server
      dockerfile: Dockerfile
    environment:
      EULA: "TRUE"
    volumes:
      - /mnt/250a/container-mounts/minecraft/data:/data
    stdin_open: true
    tty: true
    restart: always
    network_mode: service:ts
    cap_add:
      - SYS_PTRACE
  ts:
    container_name: minecraft-ts
    image: tailscale/tailscale:latest
    env_file: tailscale.env
    environment:
      - TS_HOSTNAME=minecraft
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ./tailscale-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    # https://github.com/tailscale/tailscale/issues/12758#issuecomment-2265152534
    healthcheck:
      test: tailscale status --peers=false --json | grep -q 'Online.*true'
      start_period: 30s
      interval: 120s
      timeout: 15s
      retries: 3
    restart: always
    ports:
      # Minecraft Bedrock Edition uses both ports on both UDP and TCP to use IPv4 and IPv6 according to https://minecraft.wiki/w/Bedrock_Dedicated_Server#Connection
      - "19132:19132/udp"
      - "19132:19132/tcp"
      - "19133:19133/udp"
      - "19133:19133/tcp"
  # https://github.com/edward3h/minecraft-webhook
  webhook:
    container_name: minecraft-webhook
    image: ghcr.io/edward3h/mc-webhook:latest
    restart: always
    depends_on:
      - minecraft
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/250a/container-mounts/minecraft/webhook-config.yml:/config.yml
    healthcheck:
      test: (ls -l /proc/*/exe | grep java) || exit 1
      start_period: 30s
      interval: 120s
      timeout: 15s
      retries: 3
