services:
  minecraft:
    container_name: minecraft
    build:
      context: ./docker-minecraft-bedrock-server
      dockerfile: Dockerfile
    environment:
      EULA: "TRUE"
    volumes:
      - /mnt/250a/container-mounts/minecraft/data:/data
    stdin_open: true
    tty: true
    restart: always
    network_mode: service:ts
    cap_add:
      - SYS_PTRACE
    depends_on:
      ts:
        condition: service_healthy
  ts:
    container_name: minecraft-ts
    image: tailscale/tailscale
    env_file: tailscale.env
    environment:
      - TS_HOSTNAME=minecraft
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ./tailscale-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    # https://github.com/tailscale/tailscale/issues/12758#issuecomment-2265152534
    healthcheck:
      test: tailscale status --peers=false --json | grep -q 'Online.*true'
      start_period: 30s
      interval: 120s
      timeout: 15s
      retries: 3
    restart: always
    ports:
      # These ports are exposed here so that players on the LAN can connect to the server without going through Tailscale encryption, which uses valuable CPU resources and causes game latency.
      # These ports are HERE because the minecraft container above is running ON the ts container's network,
      # which it does so that people connecting to this game via Tailscales' magic can connect to any and all ports of the Minecraft server.
      # Minecraft Bedrock Edition uses both ports on both UDP and TCP to use IPv4 and IPv6 according to https://minecraft.wiki/w/Bedrock_Dedicated_Server#Connection
      - "19132:19132/udp"
      - "19132:19132/tcp"
      - "19133:19133/udp"
      - "19133:19133/tcp"
