services:
  beszel:
    image: henrygd/beszel
    container_name: beszel
    user: 1004:1004
    restart: no
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 8090:8090
    volumes:
      - /mnt/2000/container-mounts/beszel/data:/beszel_data
      - ./healthcheck:/healthcheck
    healthcheck:
      test: ["CMD", "/healthcheck/get-home-page"]
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
    labels:
      # For homepage
      - homepage.group=System Monitoring
      - homepage.name=Beszel
      - homepage.weight=10
      - homepage.icon=/icons/beszel.svg
      - homepage.href=${HOME_PAGE_HREF}
      - homepage.widget.type=beszel
      - homepage.widget.url=${HOME_PAGE_URL}
      - homepage.widget.systemId=${SYSTEM_ID_FOR_HOMEPAGE}
      - homepage.widget.username=${USERNAME_FOR_HOMEPAGE}
      - homepage.widget.password=${PASSWORD_FOR_HOMEPAGE}
      - homepage.widget.version=2
  # There is no tailscale for this container, it is just exposed locally and can be connected to via the host's tailscale connection.
  # That could be changed, but I didn't see the point.
  beszel-agent:
    image: henrygd/beszel-agent
    container_name: beszel-agent
    user: 1004:1004
    # This must be the ID of the Docker group.
    group_add:
      - 985
    restart: no
    # The agent must run as root to get metrics from all docker containers, so do not add the user: directive.
    # The agent must use host network mode to access network interface metrics
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # Using the mounts that I set up for homepage
      - /mnt/120/for-homepage:/extra-filesystems/120:ro
      - /mnt/250/for-homepage:/extra-filesystems/250:ro
      - /mnt/2000/for-homepage:/extra-filesystems/2000:ro
      - /mnt/22TB/for-homepage:/extra-filesystems/22TB:ro
      - ./healthcheck:/healthcheck
    environment:
      PORT: 45876
      # Do not remove quotes around the key
      KEY: ${KEY}
    healthcheck:
      test: ["CMD", "/healthcheck/checkForAgentProcess"]
      start_period: 120s
      start_interval: 5s
      interval: 5m
      timeout: 5s
      retries: 3
